services:
  # Redis for collaboration performance
  redis:
    image: redis:7-alpine
    container_name: excalidraw-redis
    networks:
      - dokploy-network
    restart: on-failure
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly no
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Your customizable Excalidraw frontend (renamed to match Dokploy)
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: excalidraw
    ports:
      - "3003:80"
    networks:
      - dokploy-network
    restart: on-failure
    stdin_open: true
    environment:
      - VITE_APP_STORAGE_BACKEND_URL=http://excalidraw-storage:8080/api/v2
      - VITE_APP_WS_SERVER_URL=http://excalidraw-room:3002
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      excalidraw-storage:
        condition: service_started
      excalidraw-room:
        condition: service_started
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.exclidraw-app-kfeve3-22-web.rule=Host(`draw.aimamin.com`)
      - traefik.http.routers.exclidraw-app-kfeve3-22-web.entrypoints=web
      - traefik.http.routers.exclidraw-app-kfeve3-22-web.middlewares=redirect-to-https@file
      - traefik.http.routers.exclidraw-app-kfeve3-22-web.service=exclidraw-app-kfeve3-22-websecure
      - traefik.http.routers.exclidraw-app-kfeve3-22-websecure.rule=Host(`draw.aimamin.com`)
      - traefik.http.routers.exclidraw-app-kfeve3-22-websecure.entrypoints=websecure
      - traefik.http.routers.exclidraw-app-kfeve3-22-websecure.tls.certresolver=letsencrypt
      - traefik.http.services.exclidraw-app-kfeve3-22-websecure.loadbalancer.server.port=80

  # Storage backend for saving/sharing drawings with SQLite
  excalidraw-storage:
    image: kiliandeca/excalidraw-storage-backend:latest
    platform: linux/amd64
    container_name: excalidraw-storage
    ports:
      - "9080:8080"
    networks:
      - dokploy-network
    restart: on-failure
    environment:
      - PORT=8080
      - GLOBAL_PREFIX=/api/v2
      - STORAGE_URI=sqlite:///app/data/excalidraw.db
      - LOG_LEVEL=warn
      - REDIS_URL=redis://redis:6379  # Add Redis connection
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy

  # Collaboration server for real-time collaboration
  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    platform: linux/amd64
    container_name: excalidraw-room
    ports:
      - "3002:3002"
    networks:
      - dokploy-network
    restart: on-failure
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379  # Add Redis connection
      - "REDIS_KEY_PREFIX=excalidraw:"   # Optional: namespace your keys
    depends_on:
      redis:
        condition: service_healthy

volumes:
  notused:
  redis_data:  # Add Redis data volume

networks:
  dokploy-network:
    external: true